### ISSUE TITLE
Consider enabling close-on-exec by default.

### ISSUE THREAD

**Issue by de-vri-es** [lucab/memfd-rs#17]
First of all, thanks for the library. Very useful :)

There's one papercut that I'm a bit worried about: the close-on-exec flag.

File descriptors should almost always be close-on-exec. The only exception that I am aware of is purposefully having file descriptors inherited by forked processes, which is relatively rare. If the flag is not enabled, any unaware child process will leak the file descriptor.

I'm a bit worried that it is very easy to forget to enable it with the current API.

Would you consider changing the default value of `close-on-exec` to true? If so, I can submit a PR if you prefer (or even roll it up with the open PR, depending on timing).

**Comment by nagisa** [comment]
Would be a breaking change, so might make sense to think if we have any others we might want to make while at it.

**Comment by de-vri-es** [comment]
Indeed. #16 also includes a breaking change now, since it replaces `Either` with `Result` in an existing public call (as discussed with @lucab). Could be a good candidate to throw this in with.

Still a good idea to consider if there's more, of course :)

I didn't see any other breaking changes I would like to make myself.

**Comment by lucab** [comment]
That sounds reasonable to me, perhaps an helper method to set/unset it externally too. It looks like we'd want to go for a 0.4.0 after both PRs are merged.

**Comment by de-vri-es** [comment]
> That sounds reasonable to me, perhaps an helper method to set/unset it externally too. It looks like we'd want to go for a 0.4.0 after both PRs are merged.

Right, then you can create it with cloexec and later still decide to pass it to a forked process (could even be a runtime decision then). Sounds good :+1: 

If nobody beats me to it I'll also submit a PR for that :)
