### ISSUE TITLE
Consider making a release

### ISSUE THREAD

**Issue by diwic** [lucab/memfd-rs#21]
Hi!

I'm using this crate for my [IPC experiments](https://github.com/diwic/shmem-ipc) and it would be nice with a release without the `either` crate dependency, which is in git master.

Thanks in advance!

**Comment by de-vri-es** [comment]
There were some open discussions on other things to squeeze into a semver bump (#19 and #20). But considering that those have kinda stalled, it may make sense to do a release without those.

**Comment by lucab** [comment]
@diwic absolutely! @nagisa is currently re-spinning https://github.com/lucab/memfd-rs/pull/15, I'll leave some room to hopefully land that before opening a release PR for 0.4.0.

**Comment by lucab** [comment]
Tagged: https://github.com/lucab/memfd-rs/releases/tag/v0.4.0
Published: https://crates.io/crates/memfd/0.4.0

**Comment by diwic** [comment]
Thanks!
