### ISSUE TITLE
please include license files in repo + published crates

### ISSUE THREAD

**Issue by decathorpe** [lucab/memfd-rs#34]
I'm working on packaging wasmtime for Fedora Linux, and this crate is now a dependency of wasmtime-runtime. It currently does not contain the license text for the Apache-2.0 or MIT license, both of which licenses require a license text to be present with redistributed sources. I assume the missing LICENSE-* files are a simple oversight, because your other crates do contain them - but it prevents me from proceeding with a package review for Fedora.

**Comment by nagisa** [comment]
> I assume the missing LICENSE-* files are a simple oversight

It is somewhat widely accepted that a SPDX reference to the licenses in `Cargo.toml` is sufficient to indicate the licensing of the code, but I did make a PR to add the files if it helps downstream packaging story.

**Comment by nagisa** [comment]
v0.5.1

**Comment by decathorpe** [comment]
Thank you!

> a SPDX reference to the licenses in Cargo.toml is sufficient to indicate the licensing of the code

This is true, it is enough to *specify* the license. However, the Apache-2.0 and MIT licenses both have their own terms, which require redistributed sources to contain a copy of the respective license text. So for these two licenses, adding the text itself is required, as well.
