### ISSUE TITLE
The error type does not implement `Sync`.

### ISSUE THREAD

**Issue by nagisa** [lucab/memfd-rs#6]
It is a good practice for errors to implement `std::error::Error + Send + Sync + 'static` nowadays. `memfd` only implements `std::error::Error + Send + 'static` which necessitates putting this error into a mutex to make it also `Sync` – unnecessarily so!

Best way to achieve this is probably to use the more modern `thiserror` instead of `error_chain`.

**Comment by lucab** [comment]
> Best way to achieve this is probably to use the more modern thiserror instead of error_chain.

Happy to do that. I've recently been looking at [snafu](https://docs.rs/snafu/0.6.1/snafu/) for my other crates, but I don't have a strong preference and `thiserror` looks nice!
